server:
  port: 0

management:
  security:
    enabled: false

swagger:
  enabled: true

eureka:
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 10

oneorder:
  consecutiveErrorThreshold: 4
  backOff:
    delay: 5000

boomi:
  quadro:
    exportRules:
      BULGARIA: OFF
      CZECHIA: OFF
      GREECE: OFF
      HUNGARY: OFF
      SLOVENIA: OFF
      SPAIN: OFF
      ITALY: OFF
      POLAND: SEA,AIR

---
spring:
  profiles: dev
  data:
    mongodb:
      host: 10.1.70.92
      port: 27017
      database: crm-quote-queue
      authentication-database: crm-quote-queue
      mechanism: SCRAM-SHA-1
  redis:
    host: 10.1.70.92
    port: 6379
  rabbitmq:
    host: 10.1.70.92
    port: 5672

security:
  host: 10.1.70.92
  oauth2:
    client:
      checkTokenUri: http://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: http://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: http://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: http://${security.host}:9999/auth/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.70.92:8761/eureka/

boomi:
  quadro:
    endpoint: http://193.200.188.2:4091/ws/simple/createQuoteTestOOTest
    username: oneorder@ekollojistik-ZM3E1W
    password: 453830c7-64bf-47f7-9179-0ed458a03750

---
spring:
  profiles: test
  data:
    mongodb:
      host: 10.1.69.156
      port: 27017
      database: crm-quote-queue
      authentication-database: admin
      mechanism: SCRAM-SHA-1
      username: root
      password: one+order
  redis:
    host: 10.1.69.156
    port: 6379
    password: one+order
  rabbitmq:
    host: 10.1.69.156
    port: 5672

security:
  host: oneorder-test.ekol.com
  oauth2:
    client:
      checkTokenUri: https://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: https://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: https://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: https://${security.host}:9999/auth/user
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.69.156:8761/eureka/

boomi:
  quadro:
    endpoint: http://S-BOOMI02:4080/ws/simple/createProposalOO
    username: oneorder@ekollojistik-ZM3E1W
    password: 453830c7-64bf-47f7-9179-0ed458a03750

---
spring:
  profiles: prod
  data:
    mongodb:
      host: 10.1.70.244
      port: 27017
      database: crm-quote-queue
      authentication-database: admin
      mechanism: SCRAM-SHA-1
      username: root
      password: one+order
  redis:
    host: 10.1.70.244
    port: 6379
    password: one+order
  rabbitmq:
    host: 10.1.70.244
    port: 5672

security:
  host: oneorder.ekol.com
  oauth2:
    client:
      checkTokenUri: https://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: https://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: https://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: https://${security.host}:9999/auth/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.69.85:8761/eureka/

boomi:
  quadro:
    endpoint: http://S-BOOMI01.ekol.com:4080/ws/simple/createProposalOO
    username: oneorder@ekollojistik-ZM3E1W
    password: 5a9cc2c9-25e8-4a4b-abd1-433c0cd4cabb

---
spring:
  profiles: integration
  rabbitmq:
    host: 10.1.70.92
    port: 5672

redis:
  host: 10.1.70.92
  port: 6379

security:
  host: localhost
  oauth2:
    client:
      checkTokenUri: http://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: http://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: http://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: http://${security.host}:9999/auth/user

eureka:
  client:
    enabled: false