server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0
    responseCacheUpdateIntervalMs: 5000
    renewalPercentThreshold: 0.6

---
spring:
  profiles: dev

eureka:
  instance:
    preferIpAddress: true
    hostname: 10.1.70.92
    leaseExpirationDurationInSeconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: test

eureka:
  instance:
    preferIpAddress: true
    hostname: 10.1.69.156
    leaseExpirationDurationInSeconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: prod

eureka:
  instance:
    hostname: 10.1.69.85
  server:
    responseCacheUpdateIntervalMs: 15000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/


---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

