server:
  port: 0

management:
  security:
    enabled: false

swagger:
  enabled: true

eureka:
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 10

oneorder:
  consecutiveErrorThreshold: 3
  backOff:
    delay: 60000

---
spring:
  profiles: dev
  data:
    mongodb:
      host: 10.1.70.92
      port: 27017
      database: order-queue
      authentication-database: order-queue
      mechanism: SCRAM-SHA-1
  rabbitmq:
    host: 10.1.70.92
    port: 5672
  redis:
    host: 10.1.70.92
    port: 6379
  metrics:
    influx:
      enabled: false
      uri: http://localhost:8086
      db: oneorder
      step: PT30S
    servo:
      enabled: false
    web:
      client:
        recordRequestPercentiles: true
      server:
        autoTimeRequests: false

security:
  host: 10.1.70.92
  oauth2:
    client:
      checkTokenUri: http://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: http://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: http://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: http://${security.host}:9999/auth/user

outlook:
  redirectUrl: http://localhost:8765/outlook-service/outlook/authorize

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.70.92:8761/eureka/

boomi:
  quadro:
    endpoint: http://my-json-server.typicode.com/typicode/demo/posts
    username: sample
    password: sample

---
spring:
  profiles: test
  data:
    mongodb:
      host: 10.1.69.156
      port: 27017
      database: order-queue
      authentication-database: admin
      mechanism: SCRAM-SHA-1
      username: root
      password: one+order
  rabbitmq:
    host: 10.1.69.156
    port: 5672
  redis:
    host: 10.1.69.156
    port: 6379
    password: one+order

security:
  host: oneorder-test.ekol.com
  oauth2:
    client:
      checkTokenUri: https://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: https://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: https://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: https://${security.host}:9999/auth/user
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.69.156:8761/eureka/

boomi:
  quadro:
    endpoint: http://S-BOOMI02:4080/ws/simple/createOrderOO
    username: oneorder@ekollojistik-ZM3E1W
    password: 453830c7-64bf-47f7-9179-0ed458a03750

---
spring:
  profiles: prod
  data:
    mongodb:
      host: 10.1.70.244
      port: 27017
      database: order-queue
      authentication-database: admin
      mechanism: SCRAM-SHA-1
      username: root
      password: one+order
  redis:
    host: 10.1.70.244
    port: 6379
    password: one+order
  rabbitmq:
    host: 10.1.70.244
    port: 5672
  metrics:
    influx:
      enabled: true
      uri: http://10.1.70.244:8086
security:
  host: oneorder.ekol.com
  oauth2:
    client:
      checkTokenUri: https://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: https://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: https://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: https://${security.host}:9999/auth/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.69.85:8761/eureka/

boomi:
  quadro:
    endpoint: http://S-BOOMI01.ekol.com:4080/ws/simple/createOrderOOProduction
    username: oneorder@ekollojistik-ZM3E1W
    password: 5a9cc2c9-25e8-4a4b-abd1-433c0cd4cabb

---
spring:
  profiles: integration
  rabbitmq:
    host: 10.1.70.92
    port: 5672

redis:
  host: 10.1.70.92
  port: 6379

security:
  host: localhost
  oauth2:
    client:
      checkTokenUri: http://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: http://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: http://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: http://${security.host}:9999/auth/user

eureka:
  client:
    enabled: false

boomi:
  quadro:
    endpoint: http://my-json-server.typicode.com/typicode/demo/posts
    username: sample
    password: sample
