server:
  port: 0

management:
  security:
    enabled: false
  metrics:
    export:
      influx:
        enabled: false
        uri: http://localhost:8086
        db: oneorder
        step: PT30S
    
eureka:
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 10

swagger:
  enabled: true

---
spring:
  profiles: dev
  rabbitmq:
    host: 10.1.70.92
    port: 5672
  redis:
    host: 10.1.70.92
    port: 6379
  data:
    mongodb:
      host: 10.1.70.92
      port: 27017
      database: pricing-calculation-log

security:
  host: 10.1.70.92
  oauth2:
    client:
      checkTokenUri: http://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: http://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: http://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: http://${security.host}:9999/auth/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.70.92:8761/eureka/
      
---
spring:
  profiles: test
  rabbitmq:
    host: 10.1.69.156
    port: 5672
  redis:
    host: 10.1.69.156
    port: 6379
    password: one+order
  data:
    mongodb:
      host: 10.1.69.156
      port: 27017
      database: pricing-calculation-log
      authentication-database: admin
      mechanism: SCRAM-SHA-1
      username: root
      password: one+order

security:
  host: oneorder-test.ekol.com
  oauth2:
    client:
      checkTokenUri: https://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: https://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: https://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: https://${security.host}:9999/auth/user
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.69.156:8761/eureka/

---
spring:
  profiles: prod
  rabbitmq:
    host: 10.1.70.244
    port: 5672
  redis:
    host: 10.1.70.244
    port: 6379
    password: one+order
  data:
    mongodb:
      host: 10.1.70.244
      port: 27017
      database: pricing-calculation-log
      authentication-database: admin
      mechanism: SCRAM-SHA-1
      username: root
      password: one+order

security:
  host: oneorder.ekol.com
  oauth2:
    client:
      checkTokenUri: https://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: https://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: https://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: https://${security.host}:9999/auth/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.69.85:8761/eureka/

management:
  metrics:
    export:
      influx:
        enabled: true
        uri: http://10.1.70.244:8086
        
---
spring:
  profiles: integration

liquibase:
  changeLog: classpath:/db/changelog-integration-test.xml
  contexts: integration
---
spring:
  profiles: docker