INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) VALUES ( 'STANDARD', 'STANDARD', 'Standard', 'MAIN', null, null);

INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'EXPRESS', 'EXPRESS', 'Express', 'MAIN', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'EXPRESS';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SUPER_EXPRESS', 'SUPER_EXPRESS', 'Super Express', 'MAIN', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'SUPER_EXPRESS';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SPEEDY', 'SPEEDY', 'Speedy', 'MAIN', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'SPEEDY';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SPEEDY_VAN', 'SPEEDY_VAN', 'Speedy Van', 'MAIN', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'SPEEDY';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SPEEDYXL', 'SPEEDYXL', 'Speedy XL', 'MAIN', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'SPEEDY';

INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'ROAD_PALLETIZATION', 'ROAD_PALLETIZATION', 'Palletization', 'EXTRA', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'ROAD_PALLETIZATION';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'ATA_CARNET', 'ATA_CARNET', 'Ata Carnet', 'EXTRA', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'ATA_CARNET';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'CAD', 'CAD', 'CAD-Cash Against Documents', 'EXTRA', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'CAD';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'TRANSIT_TRADE', 'TRANSIT_TRADE', 'Transit Trade', 'EXTRA', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'TRANSIT_SERVICE_COST';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'HEALTH_CERTIFICATION', 'HEALTH_CERTIFICATION', 'Health Certification', 'EXTRA', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'HEALTH_CERTIFICATION_COST';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'INSURANCE', 'INSURANCE', 'Insurance', 'EXTRA', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'TRANSPORTATION_INSURANCE_COST';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'ATR', 'ATR', 'ATR', 'EXTRA', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'ATR_COST';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'CERTIFICATE_OF_ORIGIN', 'CERTIFICATE_OF_ORIGIN', 'Certificate of Origin', 'EXTRA', ID, 'ROAD' FROM CRM_BILLING_ITEM where name = 'CERTIFICATE_OF_ORIGIN_COST';

INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SEA_COLLECTION', 'SEA_COLLECTION', 'Collection', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'SEA_COLLECTION';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'STORAGE', 'STORAGE', 'Storage', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'STORAGE';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'DEPOSIT_FOR_DEMURRAGE', 'DEPOSIT_FOR_DEMURRAGE', 'Deposit For Demurrage', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'DEPOSIT_FOR_DEMURRAGE';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'ENS', 'ENS', 'ENS', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'ENS';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'MANIFEST_CORRECTION', 'MANIFEST_CORRECTION', 'Manifest Correction', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'MANIFEST_CORRECTION';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SEA_BILL_OF_LADING', 'SEA_BILL_OF_LADING', 'Bill of Lading', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'SEA_BILL_OF_LADING';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'LASHING', 'LASHING', 'Lashing', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'LASHING';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SEA_MOTO_COURRIER', 'SEA_MOTO_COURRIER', 'Moto Courrier', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'SEA_MOTO_COURRIER';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SEAL', 'SEAL', 'Seal', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'SEAL';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'VGM', 'VGM', 'VGM', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'VGM';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SEA_INSURANCE', 'SEA_INSURANCE', 'Insurance', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'SEA_INSURANCE';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SEA_AGENCY_OF_PROFIT', 'SEA_AGENCY_OF_PROFIT', 'Agency Profit', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'SEA_AGENCY_OF_PROFIT';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SEA_LOCAL_COSTS', 'SEA_LOCAL_COSTS', 'Local Costs', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'SEA_LOCAL_COSTS';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'SEA_OTHER_SERVICES', 'SEA_OTHER_SERVICES', 'Other Services', 'EXTRA', ID, 'SEA' FROM CRM_BILLING_ITEM where name = 'SEA_OTHER_SERVICES';

INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'AIR_COLLECTION', 'AIR_COLLECTION', 'Collection', 'EXTRA', ID, 'AIR' FROM CRM_BILLING_ITEM where name = 'AIR_COLLECTION';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'AIR_BILL_OF_LADING', 'AIR_BILL_OF_LADING', 'Bill of Lading', 'EXTRA', ID, 'AIR' FROM CRM_BILLING_ITEM where name = 'AIR_BILL_OF_LADING';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'AIR_MOTO_COURRIER', 'AIR_MOTO_COURRIER', 'Moto Courrier', 'EXTRA', ID, 'AIR' FROM CRM_BILLING_ITEM where name = 'AIR_MOTO_COURRIER';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'AIR_PALLETIZATION', 'AIR_PALLETIZATION', 'Palletization', 'EXTRA', ID, 'AIR' FROM CRM_BILLING_ITEM where name = 'AIR_PALLETIZATION';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'AIR_INSURANCE', 'AIR_INSURANCE', 'Insurance', 'EXTRA', ID, 'AIR' FROM CRM_BILLING_ITEM where name = 'AIR_INSURANCE';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'AIR_AGENCY_OF_PROFIT', 'AIR_AGENCY_OF_PROFIT', 'Agency Profit', 'EXTRA', ID, 'AIR' FROM CRM_BILLING_ITEM where name = 'AIR_AGENCY_OF_PROFIT';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'AIR_LOCAL_COSTS', 'AIR_LOCAL_COSTS', 'Local Costs', 'EXTRA', ID, 'AIR' FROM CRM_BILLING_ITEM where name = 'AIR_LOCAL_COSTS';
INSERT INTO CRM_SERVICE_TYPE (ID, CODE, NAME, CATEGORY, BILLING_ITEM_ID, SERVICE_AREA) SELECT 'AIR_OTHER_SERVICES', 'AIR_OTHER_SERVICES', 'Other Services', 'EXTRA', ID, 'AIR' FROM CRM_BILLING_ITEM where name = 'AIR_OTHER_SERVICES';
