
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (64, 'VALUE_ADDED_SERVICES', 'Value Added Services', '6301', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (65, 'CONSUMABLE_MATERIALS', 'Consumable Materials', '6401', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (66, 'ADMINISTRATION_COST_OTHERS', 'Administration Cost & Others', '6501', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (67, 'BUILDING_TAX', 'Building Tax', '6502', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (68, 'WAREHOUSING_COSTS', 'Warehousing Costs', '6503', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (69, 'PALLET_SALES', 'Pallet Sales', '6504', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (70, 'OFFICE_RENTAL_FEE', 'Office Rental Fee', '6505', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (71, 'BULK_CARGO_UNLOADING', 'Bulk Cargo Unloading', '6506', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (72, 'OVERTIME_COST', 'Overtime Cost', '6591', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (73, 'WELCOME PACK', 'Welcome Pack', '6592', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (74, 'SHUTTLE_TRANSPORTATION', 'Shuttle Transportation', '6601', 'WHM');
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA) VALUES (75, 'DAMAGED_MISSING_GOODS', 'Damaged/Missing Goods', '6901', 'WHM');
