
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (1, 'ROAD_FREIGHT', 'Freight', '1101', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (2, 'DELIVERY_COST', 'Delivery Cost', '1161', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (3, 'DELIVERY_COST_DOT', 'Delivery Cost - DOT', '1162', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (4, 'EXPRESS', 'Express', '1201', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (5, 'SUPER_EXPRESS', 'Super Express', '1202', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (6, 'SPEEDY', 'Speedy', '1203', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (7, 'FREE_ZONE', 'Free Zone', '1211', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (8, 'ARRIVAL_CUSTOMS_AREA_DIFF', 'Arrival Customs Area Difference', '1214', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (9, 'RCO', 'Return to Country of Origin', '1215', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (10, 'ADR', 'Dangerous/ADR Goods', '1231', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (11, 'FRIGO', 'Frigo Goods', '1233', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (12, 'LONG', 'Long Goods', '1236', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (13, 'OVERSIZE', 'Oversize Goods', '1238', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (14, 'FRAGILE', 'Fragile/Valuable Goods', '1239', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (15, 'ARRIVAL_CUSTOMS_COST', 'Arrival Customs Cost', '1402', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (16, 'ATA_CARNET', 'Ata Carnet', '1412', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (17, 'EXIT_CUSTOMS_COST','Exit Customs Cost', '1451', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (18, 'ATR_COST', 'ATR Cost','1461','ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (19, 'CAD', 'CAD-Cash Against Documents', '1521', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (20, 'AGENCY_COMMISSION_COST', 'Agency Commission Cost', '1553', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (21, 'ROAD_PALLETIZATION', 'Palletization', '1613', 'ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (22, 'TRANSPORTATION_INSURANCE_COST', 'Transportation Insurance Costs','1801','ROAD', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (23, 'CERTIFICATE_OF_ORIGIN_COST', 'Certificate of Origin Cost','1455','ROAD', 0);

INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (24, 'SEA_FREIGHT', 'Freight', '3101', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (25, 'SEA_IMO', 'Dangerous Goods (IMO)', '3231', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (26, 'SEA_COLLECTION', 'Collection Costs', '3151', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (27, 'SEA_BILL_OF_LADING', 'Bill of Lading Fee', '3501', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (28, 'SEA_MOTO_COURRIER', 'Moto Courrier Costs', '3581', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (29, 'SEA_INSURANCE', 'Insurance Cost', '3801', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (30, 'SEA_AGENCY_OF_PROFIT', 'Agency Commission Cost', '3141', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (31, 'SEA_LOCAL_COSTS', 'Local Costs', '3302', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (32, 'SEA_EXW_COST', 'EXW Cost', '3451', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (33, 'SEA_IMPORT_CUSTOMS_CLEARANCE', 'Import Customs Clearance Costs', '3450', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (34, 'SEA_OTHER_SERVICES', 'Other Services', '3915', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (35, 'STORAGE','Storage Costs', '3601', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (36, 'DEPOSIT_FOR_DEMURRAGE', 'Deposit For Demurrage', '3272', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (37, 'ENS', 'ENS Costs', '3326', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (38, 'MANIFEST_CORRECTION', 'Correction Costs of Manifest', '3502', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (39, 'LASHING', 'Lashing Fee', '3333', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (40, 'SEAL','Seal Costs', '3408', 'SEA', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (41, 'VGM','VGM Costs', '3325', 'SEA', 0);

INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (42, 'AIR_FREIGHT', 'Freight', '2101', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (43, 'AIR_IMO', 'Dangerous Goods (IMO)', '2231', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (44, 'AIR_COLLECTION', 'Collection Costs', '2151', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (45, 'AIR_BILL_OF_LADING', 'AWB Cost', '2501', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (46, 'AIR_PALLETIZATION', 'Palletization', '2622', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (47, 'AIR_MOTO_COURRIER', 'Moto Courrier Costs', '3581', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (48, 'AIR_INSURANCE', 'Insurance Cost', '2801', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (49, 'AIR_AGENCY_OF_PROFIT', 'Agency Commission Cost', '2141', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (50, 'AIR_LOCAL_COSTS', 'Local Costs', '2301', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (51, 'AIR_EXW_COST', 'EXW Cost', '2155', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (52, 'AIR_IMPORT_CUSTOMS_CLEARANCE', 'Import Customs Clearance Costs ', '2452', 'AIR', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (53, 'AIR_OTHER_SERVICES', 'Other Services', '2915', 'AIR', 0);

INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (54, 'DTR_FREIGHT', 'Freight', '9102', 'DTR', 0);

INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (55, 'WAREHOUSE_MANAGEMENT_STORAGE_COST', 'Storage Cost', '6101', 'WHM', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (56, 'WAREHOUSE_MANAGEMENT_HANDLING_COST', 'Handling Cost','6201', 'WHM', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (57, 'ORDER_PREPERATION_COST', 'Order Preperation Cost','6251', 'WHM', 0);

INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (58, 'BONDED_WAREHOUSE_STORAGE_COST', 'Storage Cost','7101', 'BWH', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (59, 'BONDED_WAREHOUSE_HANDLING_COST', 'Handling Cost','7201', 'BWH', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (60, 'HANDLING_COST_PALLETIZED_GOODS', 'Handling Cost (Palletized Goods)','7202', 'BWH', 0);
INSERT INTO CRM_BILLING_ITEM (ID, NAME, DESCRIPTION, CODE, SERVICE_AREA, DELETED) VALUES (61, 'HANDLING_COST_NON_PALLETIZED_COST', 'Handling Cost (Non Palletized Goods)','7203', 'BWH', 0);