insert into Country values(seq_country.nextval, 'AZERBAIJAN', 'AZ', '994', '#', 0, null,'migrated','az', null, 'AZM', 1);
insert into Country values(seq_country.nextval, 'ANDORRA', 'AD', '376', '#', 0, null,'migrated','es', null, 'ESP', 1);
insert into Country values(seq_country.nextval, 'UNITED ARAB EMIRATES', 'AE', '971', '#', 0, null,'migrated','ar', null, 'AED', 1);
insert into Country values(seq_country.nextval, 'ANTIGUA', 'AG', '1', '#', 0, null,'migrated','en', null, 'XCD', 1);
insert into Country values(seq_country.nextval, 'ANGUILLA', 'AI', '1', '#', 0, null,'migrated','en', null, 'XCD', 0);
insert into Country values(seq_country.nextval, 'ALBANIA', 'AL', '355', '#', 0, null,'migrated','sq', null, 'ALL', 1);
insert into Country values(seq_country.nextval, 'ARMENIA', 'AM', '374', '#', 0, null,'migrated','hy', null, 'AMD', 1);
insert into Country values(seq_country.nextval, 'NETHERLANDS ANTILLES', 'AN', '599', '#', 0, null,'migrated','en', null, 'ANG', 0);
insert into Country values(seq_country.nextval, 'ANGOLA', 'AO', '244', '#', 0, null,'migrated','en', null, 'AOK', 0);
insert into Country values(seq_country.nextval, 'AUSTRIA', 'AT', '43', '#', 0, null,'migrated','de', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'AUSTRALIA', 'AU', '61', '#', 0, null,'migrated','en', null, 'AUD', 0);
insert into Country values(seq_country.nextval, 'ARUBA', 'AW', '297', '#', 0, null,'migrated','en', null, 'AWG', 0);
insert into Country values(seq_country.nextval, 'BOSNIA & HERZOGOVINA', 'BA', '387', '#', 0, null,'migrated','bs', null, 'BAD', 1);
insert into Country values(seq_country.nextval, 'BARBADOS', 'BB', '1', '#', 0, null,'migrated','en', null, 'BBD', 0);
insert into Country values(seq_country.nextval, 'BANGLADESH', 'BD', '880', '#', 0, null,'migrated','en', null, 'BDT', 0);
insert into Country values(seq_country.nextval, 'BELGIUM', 'BE', '32', '#', 0, null,'migrated','fr', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'BURKINA FASO', 'BF', '226', '#', 0, null,'migrated','en', null, 'XOF', 0);
insert into Country values(seq_country.nextval, 'BULGARIA', 'BG', '359', '#', 0, null,'migrated','bg', null, 'BGN', 1);
insert into Country values(seq_country.nextval, 'BAHRAIN', 'BH', '973', '#', 0, null,'migrated','en', null, 'BHD', 0);
insert into Country values(seq_country.nextval, 'BURUNDI', 'BI', '257', '#', 0, null,'migrated','en', null, 'BIF', 0);
insert into Country values(seq_country.nextval, 'BERMUDA', 'BM', '1', '#', 0, null,'migrated','en', null, 'BMD', 0);
insert into Country values(seq_country.nextval, 'BRUNEI', 'BN', '673', '#', 0, null,'migrated','en', null, 'BND', 0);
insert into Country values(seq_country.nextval, 'BOLIVIA', 'BO', '591', '#', 0, null,'migrated','en', null, 'BOB', 0);
insert into Country values(seq_country.nextval, 'BRAZIL', 'BR', '55', '#', 0, null,'migrated','en', null, 'BRR', 0);
insert into Country values(seq_country.nextval, 'BHUTAN', 'BT', '975', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'BOTSWANA', 'BW', '267', '#', 0, null,'migrated','en', null, 'BWP', 0);
insert into Country values(seq_country.nextval, 'BELARUS', 'BY', '375', '#', 0, null,'migrated','be', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'BELIZE', 'BZ', '501', '#', 0, null,'migrated','en', null, 'BZD', 0);
insert into Country values(seq_country.nextval, 'CANADA', 'CA', '1', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CENTRAL AFRICAN REPUBLIC', 'CF', '236', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CONGO, REP. OF', 'CG', '242', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'IVORY COAST', 'CI', '225', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'COOK ISLANDS', 'CK', '682', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CHILE', 'CL', '56', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CAMEROON', 'CM', '237', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CHINA', 'CN', '86', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'COLOMBIA', 'CO', '57', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CUBA', 'CU', '53', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CAPE VERDE ISLANDS', 'CV', '238', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CHRISTMAS ISLAND', 'CX', '672', '#', 0, null,'migrated','en', null, 'AUD', 0);
insert into Country values(seq_country.nextval, 'CYPRUS', 'CY', '357', '#', 0, null,'migrated','el', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'CZECH REPUBLIC', 'CZ', '420', '#', 0, null,'migrated','cs', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'DJIBOUTI', 'DJ', '253', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'DOMINICA', 'DM', '1', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'ALGERIA', 'DZ', '213', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'ECUADOR', 'EC', '593', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'ESTONIA', 'EE', '372', '#', 0, null,'migrated','et', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'EGYPT', 'EG', '20', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'ERITREA', 'ER', '291', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'ETHIOPIA', 'ET', '0', '#', 0, null,'migrated','en', null, 'EUR', 0);
insert into Country values(seq_country.nextval, 'FINLAND', 'FI', '358', '#', 0, null,'migrated','fi', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'FALKLAND ISLANDS', 'FK', '500', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MICRONESIA', 'FM', '691', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'FAEROE ISLANDS', 'FO', '298', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'GABON', 'GA', '241', '#', 0, null,'migrated','en', null, 'XAF', 0);
insert into Country values(seq_country.nextval, 'UNITED KINGDOM', 'GB', '44', '#', 0, null,'migrated','en', null, 'GBP', 1);
insert into Country values(seq_country.nextval, 'GRENADA', 'GD', '1', '#', 0, null,'migrated','en', null, 'XCD', 0);
insert into Country values(seq_country.nextval, 'FRENCH GUIANA', 'GF', '594', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'GHANA', 'GH', '233', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'GIBRALTAR', 'GI', '350', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'GREENLAND', 'GL', '299', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'GAMBIA', 'GM', '220', '#', 0, null,'migrated','en', null, 'GMD', 0);
insert into Country values(seq_country.nextval, 'GUADELOUPE', 'GP', '590', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'EQUATORIAL GUINEA', 'GQ', '240', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'GREECE', 'GR', '30', '#', 0, null,'migrated','el', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'GUATEMALA', 'GT', '502', '#', 0, null,'migrated','en', null, 'GTQ', 0);
insert into Country values(seq_country.nextval, 'GUAM', 'GU', '1', '#', 0, null,'migrated','en', null, 'USD', 0);
insert into Country values(seq_country.nextval, 'GUINEA-BISSAU', 'GW', '245', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'HONG KONG', 'HK', '852', '#', 0, null,'migrated','en', null, 'HKD', 0);
insert into Country values(seq_country.nextval, 'HONDURAS', 'HN', '504', '#', 0, null,'migrated','en', null, 'HNL', 0);
insert into Country values(seq_country.nextval, 'CROATIA', 'HR', '385', '#', 0, null,'migrated','hr', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'HAITI', 'HT', '509', '#', 0, null,'migrated','en', null, 'HTG', 0);
insert into Country values(seq_country.nextval, 'HUNGARY', 'HU', '36', '#', 0, null,'migrated','hu', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'INDONESIA', 'ID', '62', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'IRELAND', 'IE', '353', '#', 0, null,'migrated','en', null, 'IRR', 1);
insert into Country values(seq_country.nextval, 'INDIA', 'IN', '91', '#', 0, null,'migrated','gu', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'IRAQ', 'IQ', '964', '#', 0, null,'migrated','ar', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'IRAN', 'IR', '98', '#', 0, null,'migrated','fa', null, 'IRR', 1);
insert into Country values(seq_country.nextval, 'ICELAND', 'IS', '354', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'JAMAICA', 'JM', '1', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'JORDAN', 'JO', '962', '#', 0, null,'migrated','ar', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'KENYA', 'KE', '254', '#', 0, null,'migrated','en', null, 'KES', 0);
insert into Country values(seq_country.nextval, 'KYRGYZSTAN', 'KG', '996', '#', 0, null,'migrated','ky', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'CAMBODIA', 'KH', '855', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'KIRIBATI', 'KI', '686', '#', 0, null,'migrated','en', null, 'AUD', 0);
insert into Country values(seq_country.nextval, 'COMOROS', 'KM', '269', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'KOREA (NORTH)', 'KP', '850', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'KOREA (SOUTH)', 'KR', '82', '#', 0, null,'migrated','ko', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'KUWAIT', 'KW', '965', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'CAYMAN ISLANDS', 'KY', '1', '#', 0, null,'migrated','en', null, 'KYD', 0);
insert into Country values(seq_country.nextval, 'KAZAKHSTAN', 'KZ', '7', '#', 0, null,'migrated','kk', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'LAOS', 'LA', '856', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'LEBANON', 'LB', '961', '#', 0, null,'migrated','ar', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'ST. LUCIA', 'LC', '1', '#', 0, null,'migrated','en', null, 'XCD', 0);
insert into Country values(seq_country.nextval, 'SRI LANKA', 'LK', '94', '#', 0, null,'migrated','en', null, 'LKR', 0);
insert into Country values(seq_country.nextval, 'LIBERIA', 'LR', '231', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'LESOTHO', 'LS', '266', '#', 0, null,'migrated','en', null, 'LSL', 0);
insert into Country values(seq_country.nextval, 'LITHUANIA', 'LT', '370', '#', 0, null,'migrated','lt', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'LIBYA', 'LY', '218', '#', 0, null,'migrated','en', null, 'LYD', 0);
insert into Country values(seq_country.nextval, 'MOROCCO', 'MA', '212', '#', 0, null,'migrated','ar', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'MONACO', 'MC', '377', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MOLDOVA', 'MD', '373', '#', 0, null,'migrated','ro', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'MARSHALL ISLANDS', 'MH', '692', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MACEDONIA', 'MK', '389', '#', 0, null,'migrated','mk', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'MALI', 'ML', '223', '#', 0, null,'migrated','en', null, 'AED', 0);
insert into Country values(seq_country.nextval, 'MYANMAR', 'MM', '95', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MONGOLIA', 'MN', '976', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MACAU', 'MO', '853', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MAURITANIA', 'MR', '222', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MONTSERRAT', 'MS', '1', '#', 0, null,'migrated','en', null, 'XCD', 0);
insert into Country values(seq_country.nextval, 'MALTA', 'MT', '356', '#', 0, null,'migrated','mt', null, 'MTL', 1);
insert into Country values(seq_country.nextval, 'MAURITIUS', 'MU', '230', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MALDIVES', 'MV', '960', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MEXICO', 'MX', '52', '#', 0, null,'migrated','es', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'MALAYSIA', 'MY', '60', '#', 0, null,'migrated','ms', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'MOZAMBIQUE', 'MZ', '258', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'NAMIBIA', 'NA', '264', '#', 0, null,'migrated','en', null, 'NAD', 0);
insert into Country values(seq_country.nextval, 'NEW CALEDONIA', 'NC', '687', '#', 0, null,'migrated','en', null, 'XPF', 0);
insert into Country values(seq_country.nextval, 'NORFOLK ISLAND', 'NF', '672', '#', 0, null,'migrated','en', null, 'AUD', 0);
insert into Country values(seq_country.nextval, 'NIGERIA', 'NG', '234', '#', 0, null,'migrated','en', null, 'NGN', 0);
insert into Country values(seq_country.nextval, 'NICARAGUA', 'NI', '505', '#', 0, null,'migrated','en', null, 'NIC', 0);
insert into Country values(seq_country.nextval, 'NORWAY', 'NO', '47', '#', 0, null,'migrated','nb', null, 'NOK', 1);
insert into Country values(seq_country.nextval, 'NEPAL', 'NP', '977', '#', 0, null,'migrated','en', null, 'NPR', 0);
insert into Country values(seq_country.nextval, 'NAURU', 'NR', '674', '#', 0, null,'migrated','en', null, 'AUD', 0);
insert into Country values(seq_country.nextval, 'NEW ZEALAND', 'NZ', '64', '#', 0, null,'migrated','en', null, 'NZD', 0);
insert into Country values(seq_country.nextval, 'OMAN', 'OM', '968', '#', 0, null,'migrated','ar', null, 'OMR', 1);
insert into Country values(seq_country.nextval, 'PANAMA', 'PA', '507', '#', 0, null,'migrated','en', null, 'PAB', 0);
insert into Country values(seq_country.nextval, 'PERU', 'PE', '51', '#', 0, null,'migrated','en', null, 'PEN', 0);
insert into Country values(seq_country.nextval, 'FRENCH POLYNESIA', 'PF', '689', '#', 0, null,'migrated','en', null, 'XPF', 0);
insert into Country values(seq_country.nextval, 'PHILIPPINES', 'PH', '63', '#', 0, null,'migrated','en', null, 'PHP', 1);
insert into Country values(seq_country.nextval, 'PAKISTAN', 'PK', '92', '#', 0, null,'migrated','en', null, 'PKR', 0);
insert into Country values(seq_country.nextval, 'POLAND', 'PL', '48', '#', 0, null,'migrated','pl', null, 'PLN', 1);
insert into Country values(seq_country.nextval, 'ST. PIERRE & MIQUELON', 'PM', '508', '#', 0, null,'migrated','en', null, 'FRF', 0);
insert into Country values(seq_country.nextval, 'PUERTO RICO', 'PR', '1', '#', 0, null,'migrated','en', null, 'USD', 0);
insert into Country values(seq_country.nextval, 'PORTUGAL', 'PT', '351', '#', 0, null,'migrated','pt', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'PALAU', 'PW', '680', '#', 0, null,'migrated','en', null, 'USD', 0);
insert into Country values(seq_country.nextval, 'QATAR', 'QA', '974', '#', 0, null,'migrated','ar', null, 'QAR', 1);
insert into Country values(seq_country.nextval, 'REUNION', 'RE', '262', '#', 0, null,'migrated','en', null, 'FRF', 0);
insert into Country values(seq_country.nextval, 'RUSSIA', 'RU', '7', '#', 0, null,'migrated','ru', null, 'R', 1);
insert into Country values(seq_country.nextval, 'RWANDA', 'RW', '250', '#', 0, null,'migrated','en', null, 'RWF', 0);
insert into Country values(seq_country.nextval, 'SAUDI ARABIA', 'SA', '966', '#', 0, null,'migrated','ar', null, 'SAR', 1);
insert into Country values(seq_country.nextval, 'SEYCHELLES', 'SC', '248', '#', 0, null,'migrated','en', null, 'SCR', 0);
insert into Country values(seq_country.nextval, 'SUDAN', 'SD', '249', '#', 0, null,'migrated','en', null, 'SDP', 0);
insert into Country values(seq_country.nextval, 'SINGAPORE', 'SG', '65', '#', 0, null,'migrated','en', null, 'SGD', 0);
insert into Country values(seq_country.nextval, 'ST. HELENA', 'SH', '290', '#', 0, null,'migrated','en', null, 'SHP', 0);
insert into Country values(seq_country.nextval, 'SLOVENIA', 'SI', '386', '#', 0, null,'migrated','sl', null, 'SIT', 1);
insert into Country values(seq_country.nextval, 'SLOVAKIA', 'SK', '421', '#', 0, null,'migrated','sk', null, 'SK', 1);
insert into Country values(seq_country.nextval, 'SIERRA LEONE', 'SL', '232', '#', 0, null,'migrated','en', null, 'SLL', 0);
insert into Country values(seq_country.nextval, 'SAN MARINO', 'SM', '378', '#', 0, null,'migrated','it', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'SOMALIA', 'SO', '252', '#', 0, null,'migrated','en', null, 'SOS', 0);
insert into Country values(seq_country.nextval, 'SURINAME', 'SR', '597', '#', 0, null,'migrated','en', null, 'SRG', 0);
insert into Country values(seq_country.nextval, 'SAO TOME & PRINCIPE', 'ST', '239', '#', 0, null,'migrated','en', null, 'STD', 0);
insert into Country values(seq_country.nextval, 'EL SALVADOR', 'SV', '503', '#', 0, null,'migrated','en', null, 'USD', 0);
insert into Country values(seq_country.nextval, 'SYRIA', 'SY', '963', '#', 0, null,'migrated','ar', null, 'SYP', 1);
insert into Country values(seq_country.nextval, 'LUXEMBOURG', 'LU', '352', '#', 0, null,'migrated','de', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'CHAD', 'TD', '235', '#', 0, null,'migrated','en', null, 'XAF', 0);
insert into Country values(seq_country.nextval, 'TOGO', 'TG', '228', '#', 0, null,'migrated','en', null, 'XOF', 0);
insert into Country values(seq_country.nextval, 'THAILAND', 'TH', '66', '#', 0, null,'migrated','en', null, 'THB', 0);
insert into Country values(seq_country.nextval, 'TAJIKISTAN', 'TJ', '7', '#', 0, null,'migrated','en', null, 'SUR', 0);
insert into Country values(seq_country.nextval, 'TOKELAU', 'TK', '690', '#', 0, null,'migrated','en', null, 'NZD', 0);
insert into Country values(seq_country.nextval, 'TURKMENISTAN', 'TM', '993', '#', 0, null,'migrated','tk', null, 'TMM', 1);
insert into Country values(seq_country.nextval, 'TONGA', 'TO', '676', '#', 0, null,'migrated','en', null, 'TOP', 0);
insert into Country values(seq_country.nextval, 'TURKEY', 'TR', '90', '#', 0, null,'migrated','tr', null, 'TRL', 1);
insert into Country values(seq_country.nextval, 'TRINIDAD, TOBAGO', 'TT', '1868', '#', 0, null,'migrated','en', null, 'TTD', 0);
insert into Country values(seq_country.nextval, 'TUVALU', 'TV', '688', '#', 0, null,'migrated','en', null, 'AUD', 0);
insert into Country values(seq_country.nextval, 'TAIWAN', 'TW', '886', '#', 0, null,'migrated','en', null, 'TWD', 0);
insert into Country values(seq_country.nextval, 'UKRAINE', 'UA', '380', '#', 0, null,'migrated','uk', null, 'UAH', 1);
insert into Country values(seq_country.nextval, 'UGANDA', 'UG', '256', '#', 0, null,'migrated','en', null, 'UGX', 0);
insert into Country values(seq_country.nextval, 'UNITED STATES OF AMERICA', 'US', '1', '#', 0, null,'migrated','en', null, 'USD', 0);
insert into Country values(seq_country.nextval, 'URUGUAY', 'UY', '598', '#', 0, null,'migrated','en', null, 'UYP', 0);
insert into Country values(seq_country.nextval, 'UZBEKISTAN', 'UZ', '998', '#', 0, null,'migrated','uz', null, 'UZS', 1);
insert into Country values(seq_country.nextval, 'VATICAN CITY', 'VA', '379', '#', 0, null,'migrated','en', null, 'EUR', 0);
insert into Country values(seq_country.nextval, 'VENEZUELA', 'VE', '58', '#', 0, null,'migrated','en', null, 'VEB', 0);
insert into Country values(seq_country.nextval, 'BRITISH VIRGIN ISLANDS', 'VG', '1', '#', 0, null,'migrated','en', null, 'USD', 0);
insert into Country values(seq_country.nextval, 'US VIRGIN ISLANDS', 'VI', '1', '#', 0, null,'migrated','en', null, 'USD', 0);
insert into Country values(seq_country.nextval, 'VIETNAM', 'VN', '84', '#', 0, null,'migrated','en', null, 'VND', 0);
insert into Country values(seq_country.nextval, 'VANUATU', 'VU', '678', '#', 0, null,'migrated','en', null, 'VUV', 0);
insert into Country values(seq_country.nextval, 'WALLIS & FUTUNA ISLANDS', 'WF', '681', '#', 0, null,'migrated','en', null, 'XPF', 0);
insert into Country values(seq_country.nextval, 'YUGOSLAVIA', 'YU', '391', '#', 0, null,'migrated','en', null, 'YUN', 1);
insert into Country values(seq_country.nextval, 'SOUTH AFRICA', 'ZA', '27', '#', 0, null,'migrated','en', null, 'ZAR', 1);
insert into Country values(seq_country.nextval, 'ZAMBIA', 'ZM', '260', '#', 0, null,'migrated','en', null, 'ZMK', 0);
insert into Country values(seq_country.nextval, 'ZAIRE', 'ZR', '0', '#', 0, null,'migrated','en', null, 'ZRN', 0);
insert into Country values(seq_country.nextval, 'ZIMBABWE', 'ZW', '263', '#', 0, null,'migrated','en', null, 'ZWD', 0);
insert into Country values(seq_country.nextval, 'GERMANY', 'DE', '49', '#', 0, null,'migrated','de', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'SWITZERLAND', 'CH', '41', '#', 0, null,'migrated','fr', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'FRANCE', 'FR', '33', '#', 0, null,'migrated','fr', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'SPAIN', 'ES', '34', '#', 0, null,'migrated','es', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'NETHERLANDS', 'NL', '31', '#', 0, null,'migrated','nl', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'SWEDEN', 'SE', '46', '#', 0, null,'migrated','sv', null, 'SEK', 1);
insert into Country values(seq_country.nextval, 'AMERICAN SAMOA', 'AS', '684', '#', 0, null,'migrated','en', null, 'USD', 0);
insert into Country values(seq_country.nextval, 'BENIN', 'BJ', '229', '#', 0, null,'migrated','en', null, 'XOF', 0);
insert into Country values(seq_country.nextval, 'BAHAMAS', 'BS', '1', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'COCOS-KEELING ISLANDS', 'CC', '61', '#', 0, null,'migrated','en', null, 'AUD', 0);
insert into Country values(seq_country.nextval, 'COSTA RICA', 'CR', '506', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'DOMINICAN REPUBLIC', 'DO', '1', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'FIJI ISLANDS', 'FJ', '679', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'GEORGIA', 'GE', '995', '#', 0, null,'migrated','ka', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'GUINEA (PRP)', 'GN', '224', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'GUYANA', 'GY', '592', '#', 0, null,'migrated','en', null, 'GYD', 0);
insert into Country values(seq_country.nextval, 'ISRAEL', 'IL', '972', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'JAPAN', 'JP', '81', '#', 0, null,'migrated','ja', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'ST. KITTS & NEVIS', 'KN', '1', '#', 0, null,'migrated','en', null, 'XCD', 0);
insert into Country values(seq_country.nextval, 'LATVIA', 'LV', '371', '#', 0, null,'migrated','lv', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'MARTINIQUE', 'MQ', '258', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'MALAWI', 'MW', '265', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'NIGER', 'NE', '227', '#', 0, null,'migrated','en', null, 'XOF', 0);
insert into Country values(seq_country.nextval, 'NIUE', 'NU', '683', '#', 0, null,'migrated','en', null, 'NZD', 0);
insert into Country values(seq_country.nextval, 'PAPUA NEW GUINEA', 'PG', '675', '#', 0, null,'migrated','en', null, 'PGK', 0);
insert into Country values(seq_country.nextval, 'PARAGUAY', 'PY', '595', '#', 0, null,'migrated','en', null, 'PYG', 0);
insert into Country values(seq_country.nextval, 'SOLOMON ISLANDS', 'SB', '677', '#', 0, null,'migrated','en', null, 'SCR', 0);
insert into Country values(seq_country.nextval, 'SENEGAL', 'SN', '221', '#', 0, null,'migrated','en', null, 'XOF', 0);
insert into Country values(seq_country.nextval, 'SWAZILAND', 'SZ', '268', '#', 0, null,'migrated','en', null, 'SZL', 0);
insert into Country values(seq_country.nextval, 'TUNISIA', 'TN', '216', '#', 0, null,'migrated','ar', null, 'TND', 1);
insert into Country values(seq_country.nextval, 'TANZANIA', 'TZ', '255', '#', 0, null,'migrated','en', null, 'TWD', 0);
insert into Country values(seq_country.nextval, 'ST. VINCENT, GRENADINES', 'VC', '1', '#', 0, null,'migrated','en', null, 'XCD', 0);
insert into Country values(seq_country.nextval, 'YEMEN', 'YE', '967', '#', 0, null,'migrated','en', null, 'YR', 0);
insert into Country values(seq_country.nextval, 'ARGENTINA', 'AR', '54', '#', 0, null,'migrated','en', null, 'ARA', 0);
insert into Country values(seq_country.nextval, 'DENMARK', 'DK', '45', '#', 0, null,'migrated','da', null, 'BSD', 1);
insert into Country values(seq_country.nextval, 'ITALY', 'IT', '39', '#', 0, null,'migrated','it', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'MADAGASCAR', 'MG', '261', '#', 0, null,'migrated','en', null, 'BSD', 0);
insert into Country values(seq_country.nextval, 'ROMANIA', 'RO', '40', '#', 0, null,'migrated','ro', null, 'ROL', 1);
insert into Country values(seq_country.nextval, 'SAMOA', 'WS', '685', '#', 0, null,'migrated','en', null, 'WST', 0);
insert into Country values(seq_country.nextval, 'SERBIA', 'CS', '381', '#', 0, null,'migrated','en', null, 'EUR', 0);
insert into Country values(seq_country.nextval, 'LIECHTENSTEIN', 'LI', '423', '#', 0, null,'migrated','de', null, 'CHF', 1);
insert into Country values(seq_country.nextval, 'SERBIA', 'RS', '381', '#', 0, null,'migrated','sr', null, 'RS', 1);
insert into Country values(seq_country.nextval, 'NORTH CYPRUS TURKISH REPUBLIC', 'KT', '357', '#', 0, null,'migrated','tr', null, 'TL', 1);
insert into Country values(seq_country.nextval, 'FILISTINE', 'PS', '695', '#', 0, null,'migrated','en', null, 'EUR', 0);
insert into Country values(seq_country.nextval, 'MONTENEGRO', 'ME', '382', '#', 0, null,'migrated','sr', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'AFGHANISTAN', 'AF', '93', '#', 0, null,'migrated','en', null, 'AFA', 0);
insert into Country values(seq_country.nextval, 'DEMOCRATIC REPUBLIC CONGO', 'CD', '243', '#', 0, null,'migrated','fr', null, 'CDF', 1);
insert into Country values(seq_country.nextval, 'KOSOVO', 'KV', '0', '#', 0, null,'migrated','sr', null, 'EUR', 1);
insert into Country values(seq_country.nextval, 'TURKS AND CAICOS ISLANDS', 'TC', '0', '#', 0, null,'migrated','en', null, 'USD', 0);