Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0001','Chairman','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0002','Board Member','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0003','CEO','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0004','General Manager','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0005','Asst. General Manager / Director','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0006','Manager','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0007','Asst. Manager','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0008','Sr. Supervisor','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0009','Supervisor','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0010','Specialist','ACTIVE',0);
Insert into CONTACT_TITLE (ID,CODE,NAME,STATUS,DELETED) values (seq_contacttitle.nextval,'0011','Asst. Specialist','ACTIVE',0);

Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0001','Head Quarters','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0002','Logictics','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0003','Purchasing','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0004','Business Development','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0005','Production','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0006','Production Planning','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0007','Accounting','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0008','Finance','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0009','Sales','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0010','Research & Development','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0011','Quality Control','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0012','Customer Services','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0013','Administrative Affairs','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0014','Human Resources','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0015','Marketing','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0016','Information Technologies','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0017','Maintenance Services','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0018','Supplier Chain','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0019','Foreign Trade','ACTIVE',0);
Insert into CONTACT_DEPARTMENT (ID,CODE,NAME,STATUS,DELETED) values (SEQ_CONTACTDEPARTMENT.nextval,'0020','Invoice Department','ACTIVE',0);