BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERGROUP_UIMENU CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USERGROUP_UIMENU';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 AND SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;