package ekol.orders.transportOrder.repository;

import ekol.hibernate5.domain.repository.ApplicationRepository;
import ekol.orders.transportOrder.domain.TransportOrderRuleSetWarehouseHandlingRule;


public interface TransportOrderRuleSetWarehouseHandlingRuleRepository extends ApplicationRepository<TransportOrderRuleSetWarehouseHandlingRule> {
}
