update PACKAGE_TYPE_RESTRICTION set
    MIN_WIDTH_CM = MIN_WIDTH_CM * 100, MAX_WIDTH_CM = MAX_WIDTH_CM * 100,
    MIN_LENGTH_CM = MIN_LENGTH_CM * 100, MAX_LENGTH_CM = MAX_LENGTH_CM * 100,
    MIN_HEIGHT_CM = MIN_HEIGHT_CM * 100, MAX_HEIGHT_CM = MAX_HEIGHT_CM * 100;