insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '986', 'SKALIC','SK', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '987', 'HELLAS TOROS','GR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '988', 'TARGOVIST EXPOSIT','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '990', 'CİLVEGÖZ','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '989', 'TİFLİS','GE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '991', 'LA VERPILLIERE','FR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '316', 'PENDİK GÜMRÜK','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '992', 'TUZLA SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '993', 'İNCİRLİK SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '994', 'SUBEN','AT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '995', 'ANSBACH','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '996', 'WAIDHAUS','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '997', 'REGENSBURG','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '998', 'RUSSE','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '999', 'EDİRNE GAR','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '300', 'TAŞUCU','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '100', 'AHL YOLCU SALONU','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '887', 'HABUR','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '088', 'DALAMAN HAVALİMANI','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '089', 'TOULON','FR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '101', 'RİZE','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '914', 'SPIELFELD','AT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '029', 'ANCONA','IT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '891', 'DOLJ','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '073', 'GEMLİK SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '950', 'MARSİLYA','FR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '921', 'METSELA','FI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '922', 'HAKKILA','FI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '923', 'LOVIISA','FI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '924', 'PIETESAARI','FI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '925', 'TAMPERE','FI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '926', 'TURKU','FI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '886', 'BORDER MACELJ','HR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '817', 'KARABÜK','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '090', 'KARAMAN','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '002', 'ERENKÖY','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '003', 'HALKALI TEKSTİL İHTİSAS','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '005', 'HALKALI','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '006', 'AHL SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '007', 'DİLOVASI','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '008', 'BURSA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '009', 'KAPIKULE TIR - K.ANDEROVO','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '012', 'ANKARA TIR (KAZAN)','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '015', 'EGE SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '018', 'BAYRAMPAŞA GIDA İHTİSAS','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '022', 'İZMİT AKARYAKIT','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '026', 'ANKARA NAKİLHANE VE BEDELSİZ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '031', 'ALİAĞA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '034', 'İZMİT','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '036', 'TEKİRDAĞ','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '041', 'ESENBOĞA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '045', 'KAYSERİ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '048', 'EGE RO-RO','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '050', 'KÜTAHYA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '053', 'YARIMCA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '056', 'ESKİŞEHİR','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '889', 'UŞAK','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '061', 'SAMSUN','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '065', 'GAZİANTEP','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '067', 'ÇORLU HAVALİMANI','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '072', 'GEMLİK','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '074', 'KOCAELİ SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '076', 'MALATYA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '079', 'AHL YOLCU SALONU','TR', 1, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '083', 'BİLECİK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '311', 'ZONGULDAK','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '313', 'FİNİKE GÜM MÜD','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '314', 'AVRUPA SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '888', 'GÜRBULAK','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '011', 'DERİNCE','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '013', 'ÇERKEZKÖY','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '014', 'YALOVA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '017', 'YEŞİLKÖY OTOMOTİV İHTİSAS','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '019', 'MANİSA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '021', 'AHL KARGO','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '023', 'TRABZON','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '024', 'BOLU','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '028', 'MERSİN','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '030', 'DÜZCE','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '032', 'SAKARYA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '033', 'GEBZE AKARYAKIT','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '035', 'MUDANYA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '037', 'İPSALA','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '040', 'TRAKYA İSBAŞ S.B.','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '043', 'ADNAN MENDERES HAVAALANI','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '044', 'ÇEŞME','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '046', 'ADANA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '047', 'ANTALYA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '049', 'AMBARLI RO-RO','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '051', 'NİĞDE','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '054', 'ORDU','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '055', 'İZMİR MENEMEN DERİ S.B.','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '057', 'GEBZE','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '060', 'AMBARLI','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '063', 'KÖRFEZ PETRO KİMYA GÜMRÜK MÜDÜ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '064', 'ISPARTA','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '066', 'BURSA SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '069', 'ANTALYA SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '070', 'DENİZLİ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '075', 'AKINCI GÜM.MÜD.','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '077', 'ÇORLU AVRUPA S.B.','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '078', 'İZMİR TIR','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '082', 'İZMİR GÜMRÜK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '085', 'İSKENDERUN','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '312', 'İSTANBUL DERİ SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '084', 'BANDIRMA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '315', 'İSTANBUL TRAKYA SB','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '081', 'KAHRAMANMARAŞ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '086', 'YUMURTALIK SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '892', 'MENEMEN DERİ SERBEST BÖLGE','TR', 1, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '071', 'İSTANBUL SAYMANLIK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '900', 'BAD REICHENHALL','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '901', 'PASSAU','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '910', 'TRIESTE','IT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '911', 'BARI','IT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '920', 'YSTADT CUSTOMS','SE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '912', 'SALZBURG','AT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '913', 'NICKELSDORF','AT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '931', 'LJUBLJANA','SI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '951', 'GADKI','PL', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '087', 'AYDIN','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '952', 'DİYARBAKIR','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '953', 'İZMİR YOLCU SALONU','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '956', 'KARADENİZ EREĞLİ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '954', 'MERSİN YOLCU SALONU','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '955', 'HAMZABEYLİ - LESOVO','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '957', 'SİVAS GÜMRÜK MÜD','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '959', 'İSDEMİR','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '958', 'SARP','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '960', 'İSTANBUL PAKET POSTA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '961', 'HAMZABEYLİ','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '902', 'BENSHEIM','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '903', 'LA JONQUERA','ES', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '962', 'BENSHEIM','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '963', 'BERTRANS','HU', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '964', 'KGH SPEDITON','NO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '965', 'PADBORG CUSTOM CLEARANCE','DK', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '966', 'TOLD & SKAT','DK', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '967', 'MALMÖ CUSTOMS','SE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '968', 'ANTALYA HAVA LİMANI','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '331', 'İNCİRLİK','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '969', 'GÖLCÜK SERBEST BÖLGE','TR', 1, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '970', 'SABİHA GÖKÇEN HAVALİMANI','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '915', 'BRASOV','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '971', 'İZMİR HAVALİMANI','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '972', 'FETHİYE','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '973', 'DOVER','GB', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '909', 'KEPEZ LİMAN GÜMRÜĞÜ','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '974', 'BARTIN','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '975', 'SVİLENGRAD','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '976', 'POLSPED','PL', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '977', 'EVPATORIA','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '978', 'MAINETTI ROMANIA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '979', 'SCHENKER WELS','AT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '980', 'SOFIADA STOLICHNA','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '981', 'PLOVDIV','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '982', 'CUSTOMS AIRPORT SOFIA','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '983', 'SHARIYAR','IR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '984', 'DEVA CUSTOMS 2700','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '985', 'AKSARAY','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '927', 'TAMPERE','FI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '416', 'BOTEVGRAD/SOFIJA','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '916', 'AVRUPA İÇİ GÜMRÜK','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '200', 'ANKARA GAR GÜMRÜK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '590', 'BİGA GÜMRÜK MÜDÜRLÜĞÜ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '417', 'ATHENS','GR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '419', 'AFYON','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '917', 'MANNHEIM','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '318', 'TRAKYA GÜMRÜK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '097', 'GENT','BE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '001', 'HAYDARPAŞA','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '949', 'NOVGOROD','RU', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '180', 'RAVA RUSSKA','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '020', 'BUDAPEST','HU', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '176', 'KHARKIV','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '182', 'RENİ','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '184', 'MARİBOR','SI', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '333', 'EKOL AKASYA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '422', 'BELÇİKA','BE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '896', 'BAZARGAN','IR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '895', 'MAKU','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '091', 'KRAGUJEVAC','RS', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '124', 'BASEL','CH', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '500', 'TEHRAN SHAHRIYAR','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '203', 'BATROVCI LIPOVAC','RS', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '332', 'ZEYTİNBURNU','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '433', 'ERZURUM GÜMRÜK','TR', 1, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '319', 'IRAK','IQ', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '520', 'AKTAU','KZ', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '201', 'ALAŞEHİR GÜMRÜK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '179', 'KRAKOVETS','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '185', 'BAJAKOVA','HR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '428', 'PORTEKİZ','PT', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '429', 'GHARB ','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '435', 'AZERBEYCAN','AZ', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '436', 'ANDORA','AD', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '437', 'ANTIGUA','AG', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '438', 'ARNAVUTLUK','AL', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '439', 'ERMENİSTAN','AM', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '440', 'AVUSTURYA','AT', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '441', 'BOSNA HERSEK','BA', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '442', 'BULGARİSTAN','BG', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '443', 'BEYAZ RUSYA','BY', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '444', 'KIBRIS','CY', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '445', 'ÇEK CUMHURİYETİ','CZ', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '446', 'ESTONYA','EE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '447', 'FİNLANDİYA','FI', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '448', 'İNGİLTERE','GB', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '449', 'YUNANİSTAN','GR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '450', 'HIRVATİSTAN','HR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '451', 'MACARİSTAN','HU', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '452', 'İRLANDA','IE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '453', 'HİNDİSTAN','IN', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '454', 'IRAN','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '455', 'URDUN','JO', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '456', 'KIRGIZISTAN','KG', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '457', 'GUNEY KORE','KR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '458', 'KAZAKISTAN','KZ', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '459', 'LUBNAN','LB', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '460', 'LİTVANYA','LT', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '461', 'FAS','MA', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '462', 'MOLDOVYA','MD', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '463', 'MAKEDONYA','MK', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '415', 'HUNEDOARA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '183', 'KORCZOWA','PL', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '603', 'VINNITSA','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '890', 'KAYSERİ SERBEST BÖLGE','TR', 1, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '818', 'KIRIKKALE','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '427', 'İSVİÇRE','CH', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '610', 'ELAZIĞ GÜMRÜK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '464', 'MALTA','MT', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '465', 'MEKSIKA','MX', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '466', 'MALEZYA','MY', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '467', 'NORVEÇ','NO', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '468', 'UMMAN','OM', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '469', 'FILIPINLER','PH', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '470', 'POLONYA','PL', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '471', 'KATAR','QA', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '472', 'RUSYA','RU', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '473', 'SUUDİ ARABİSTAN','SA', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '474', 'SLOVENYA','SI', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '475', 'SLOVAKYA','SK', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '476', 'SAN MARINO','SM', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '477', 'SURİYE','SY', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '478', 'LÜKSEMBURG','LU', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '479', 'TURKMENISTAN','TM', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '480', 'TÜRKİYE','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '481', 'ÖZBEKİSTAN','UZ', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '482', 'YUGOSLAVYA','YU', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '483', 'GUNEY AFRICA','ZA', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '484', 'ALMANYA','DE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '485', 'İSVEÇ','SE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '486', 'GÜRCİSTAN','GE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '487', 'JAPONYA','JP', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '488', 'LETONYA','LV', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '489', 'TUNUS','TN', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '490', 'DANİMARKA','DK', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '491', 'İTALYA','IT', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '492', 'ROMANYA','RO', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '493', 'LIECHTENSTEIN','LI', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '494', 'SERBIA','RS', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '495', 'KUZEY KIBRIS TÜRK CUMHURİYETİ','KKTC', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '004', 'ARGES','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '908', 'KAPIKULE GAR - K.ANDEROVO','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '932', 'PATRA','GR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '600', 'STARA ZAGORA','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '095', 'AKÇAKALE GÜMRÜK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '010', 'KARAKÖY YOLCU SALONU','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '027', 'ÇANAKKALE','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '173', 'İNEBOLU GÜMRÜK MÜDÜRLÜĞÜ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '940', 'SETE','FR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '191', 'OLOMOUC','CZ', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '038', 'TEKİRDAĞ RO-RO','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '112', 'BODRUM GÜMRÜK MÜDÜRLÜĞÜ','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '701', 'BRINDISI','IT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '496', 'MONTENEGRO','ME', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '497', 'KONGO DEMOKRATİK CUMHURİYETİ','CD', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '498', 'KOSOVA','KV', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '080', 'PENDİK RO-RO','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '334', 'BOSANSKI BROD','BA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '94', 'DRAZİCE','HR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '934', 'SZEGED','HU', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '202', 'SARAJEVO','BA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '501', 'TEHRAN GHARB','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '919', 'SOSNOWIEC','PL', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '194', 'LİMASOL','CY', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '204', 'HALKALI GAR','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '401', 'BUZAU','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '402', 'TIMIŞOARA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '403', 'EKOL ROMANIA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '404', 'SUCEAVA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '405', 'THESSALONIKI','GR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '406', 'ZIMNICEA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '407', 'CHIAJNA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '408', 'BRAILA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '409', 'AGIOS ATHANASIOS','GR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '410', 'RETHYMNON','GR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '118', 'MODENA','IT', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '411', 'MEUSPATH','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '123', 'APRILIA','IT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '413', 'BRAGADIRU / ILFOV','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '930', 'KÖLN','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '096', 'SADI','PL', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '350', 'SAINT AVOLD','FR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '181', 'VYSHNEVE','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '187', 'MEDYKA','PL', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '190', 'ERBİL','IRQ', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '423', 'HOLLANDA','NL', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '502', 'QAZVIN','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '503', 'TEBRIZ-SAHLAN','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '125', 'ZEEBRUGGE PORT','BE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '205', 'ÖNCÜPINAR','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '400', 'IRUN','ES', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '105', 'STOCKHOLM CUSTOMS','SE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '120', 'KOPENHAG CUSTOMS','DK', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '104', 'GÖTEBORG CUSTOMS','SE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '117', 'PADBORG CUSTOMS','DK', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '107', 'KUTY CUSTOMS','SK', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '108', 'BUCHAREST CUSTOMS','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '109', 'KAPITAN ANDREVO CUSTOMS','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '110', 'LESOVA CUSTOMS','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '111', 'KALOTINA CUSTOMS','BG', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '114', 'FURT IM WALD CUSTOMS','DE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '115', 'POZNAN CUSTOMS','PL', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '116', 'WARBERG CUSTOMS','SE', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '119', 'ODENSE CUSTOMS','DK', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '121', 'İNEGÖL GÜMRÜK MÜDÜRLÜĞÜ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '412', 'CONSTANTA','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '414', 'CALARAŞI','RO', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '317', 'BATI MARMARA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '122', 'HALKALI TREN','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '602', 'POLTOVA','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '175', 'PORUBNOE','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '177', 'ENNEREY CRD','FR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '178', 'YAGODİN','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '186', 'KREMENÇHUK','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '421', 'LAVRIO','GR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '424', 'FRANSA','FR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '425', 'UKRAYNA','UA', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '426', 'İNGİLTERE','EN', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '897', 'IJMUIDEN PORT','NL', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '898', 'ROTTERDAM PORT','NL', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '935', 'ST AVOLD ','FR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '103', 'ANKARA GÜMRÜK SAYMANLIĞI(ULUS)','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '928', 'JONKOPING CUSTOMS','SE', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '929', 'NORRE ALSLEV','DK', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '098', 'CONCOREZZO','IT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '099', 'AMATRANS MILANO','', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '750', 'MARDİN','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '188', 'SUMY','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '174', 'ODESSA','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '430', 'İSPANYA','ES', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '039', 'MERSİN SERBEST BÖLGE','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '052', 'KONYA','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '504', 'URUMIYEH','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '193', 'MARTİN','SK', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '102', 'AYVALIK','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '418', 'FERNETTİ','IT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '093', 'IKEA','IR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '918', 'NOVARA','IT', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '893', 'GİRESUN','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '751', 'GAZİANTEP SERBEST BÖLGE MÜDÜRLÜĞÜ','TR', 0, 1);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '420', 'KİEV','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '189', 'İLYCHEVSK','UA', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '894', 'ANTAKYA ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '933', 'ALSANCAK  RO-RO ALSANCAK LİMAN','TR', 1, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '434', 'ŞANLIURFA GÜMRÜK MÜDÜRLÜĞÜ','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '192', 'ÇORUM','TR', 0, 0);
insert into CUSTOMS(id, code, name, country, border, freezone) values(SEQ_CUSTOMS.nextval, '351', 'RÖSZKE','HU', 1, 0);