insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Carton','Carton',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Pallet','Pallet',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Stange','Stange',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'GitterBox','Gitter Box',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Package','Package',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Case','Case',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Crate','Crate',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Drum','Drum',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Bag','Bag',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Bale','Bale',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Bundle','Bundle',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Roll','Roll',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Box','Box',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Sack','Sack',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Barrel','Barrel',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Piece','Piece',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Parcel','Parcel',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Pair','Pair',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Tank','Tank',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Bobbin','Bobbin',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'PCS','PCS',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'EuroPallet','Euro Pallet',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'IndustryPallet','Industry Pallet',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Cover','Cover',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Can','Can',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Unpacked','Unpacked',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'IBCContainer','IBC Container',0);
insert into PACKAGE_TYPE (id, code, name, deleted) values (seq_packagetype.nextval,'Bottle','Bottle',0);