insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'1','Explosive substances and articles ',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'2','Gases',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'9','Miscellaneous dangerous substances and articles',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'3','Flammable Liquids',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'4.1','Flammable Solids, self reactive substances and solid desensitized explosives',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'4.2','Substances liable to spontaneous combustion',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'4.3','Substances which, in contact with water, emit flammable gases',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'5.1','Oxidizing substances',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'5.2','Organic peroxides',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'6.1','Toxic substances',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'6.2','Infectious substances',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'7','Radioactive substances',0)
insert into ADR_CLASS (id, code, name, deleted) values (seq_adrclass.nextval,'8','Corrosive substances',0)
