update ORDER_SHIPMENT set SEN_HANDLING_TIMEZONE = READY_AT_DATE_TIMEZONE where READY_AT_DATE_TIMEZONE is not null;
update ORDER_SHIPMENT set SEN_HANDLING_TIMEZONE = LOADING_APP_START_TIME_ZONE where LOADING_APP_START_TIME_ZONE is not null;
update ORDER_SHIPMENT set SEN_HANDLING_TIMEZONE = 'UTC' where SEN_HANDLING_TIMEZONE is null;

update ORDER_SHIPMENT set CON_HANDLING_TIMEZONE = DELIVERY_DATE_TIMEZONE where DELIVERY_DATE_TIMEZONE is not null;
update ORDER_SHIPMENT set CON_HANDLING_TIMEZONE = UNLOADING_APP_START_TIME_ZONE where UNLOADING_APP_START_TIME_ZONE is not null;
update ORDER_SHIPMENT set CON_HANDLING_TIMEZONE = 'UTC' where CON_HANDLING_TIMEZONE is null;