server:
  port: 8895

spring:
  data:
    mongodb:
      host: 10.1.70.92
      port: 27017
      database: crm-history
      authentication-database: crm-history
      mechanism: SCRAM-SHA-1
  rabbitmq:
    host: 10.1.70.92
    port: 5672

security:
  host: 10.1.70.92
  oauth2:
    client:
      checkTokenUri: http://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: http://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: http://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: http://${security.host}:9999/auth/user

outlook:
  redirectUrl: http://localhost:8765/outlook-service/outlook/authorize

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://10.1.70.92:8761/eureka/
