//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 11:14:16 AM EET 
//


package ekol.crm.account.wsclient.companycrinfo.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ekol.crm.account.wsclient.companycrinfo.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ekol.crm.account.wsclient.companycrinfo.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSCGETCOMPANYCRINFOPInput }
     * 
     */
    public WSCGETCOMPANYCRINFOPInput createWSCGETCOMPANYCRINFOPInput() {
        return new WSCGETCOMPANYCRINFOPInput();
    }

    /**
     * Create an instance of {@link WSCCOMPANYCRRESULTWType }
     * 
     */
    public WSCCOMPANYCRRESULTWType createWSCCOMPANYCRRESULTWType() {
        return new WSCCOMPANYCRRESULTWType();
    }

    /**
     * Create an instance of {@link WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW }
     * 
     */
    public WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW createWSCCOMPANYCRRESULTWTypeWSCCOMPANYCRRESULTW() {
        return new WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW();
    }

    /**
     * Create an instance of {@link WSCGETCOMPANYCRINFOPInput.ORECORDSWSCCOMPANYCRRESULTWCOUT }
     * 
     */
    public WSCGETCOMPANYCRINFOPInput.ORECORDSWSCCOMPANYCRRESULTWCOUT createWSCGETCOMPANYCRINFOPInputORECORDSWSCCOMPANYCRRESULTWCOUT() {
        return new WSCGETCOMPANYCRINFOPInput.ORECORDSWSCCOMPANYCRRESULTWCOUT();
    }

    /**
     * Create an instance of {@link WSCGETCOMPANYCRINFOPInput.ORESULTVARCHAR2OUT }
     * 
     */
    public WSCGETCOMPANYCRINFOPInput.ORESULTVARCHAR2OUT createWSCGETCOMPANYCRINFOPInputORESULTVARCHAR2OUT() {
        return new WSCGETCOMPANYCRINFOPInput.ORESULTVARCHAR2OUT();
    }

    /**
     * Create an instance of {@link WSCGETCOMPANYCRINFOPOutput }
     * 
     */
    public WSCGETCOMPANYCRINFOPOutput createWSCGETCOMPANYCRINFOPOutput() {
        return new WSCGETCOMPANYCRINFOPOutput();
    }

    /**
     * Create an instance of {@link COMPANYCRINFORSIntType }
     * 
     */
    public COMPANYCRINFORSIntType createCOMPANYCRINFORSIntType() {
        return new COMPANYCRINFORSIntType();
    }

    /**
     * Create an instance of {@link WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW.RECORDS }
     * 
     */
    public WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW.RECORDS createWSCCOMPANYCRRESULTWTypeWSCCOMPANYCRRESULTWRECORDS() {
        return new WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW.RECORDS();
    }

}
