//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 11:14:16 AM EET 
//


package ekol.crm.account.wsclient.companycrinfo.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSC_COMPANY_CR_RESULT_WType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSC_COMPANY_CR_RESULT_WType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WSC_COMPANY_CR_RESULT_W"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RECORDS"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="COMPANY_CR_INFO_RS" type="{http://xmlns.oracle.com/orawsv/QUADRO_INTERFACE/WSC_GET_COMPANY_CR_INFO_P}COMPANY_CR_INFO_RS_IntType" maxOccurs="5000" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSC_COMPANY_CR_RESULT_WType", propOrder = {
    "wsccompanycrresultw"
})
public class WSCCOMPANYCRRESULTWType {

    @XmlElement(name = "WSC_COMPANY_CR_RESULT_W", required = true)
    protected WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW wsccompanycrresultw;

    /**
     * Gets the value of the wsccompanycrresultw property.
     * 
     * @return
     *     possible object is
     *     {@link WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW }
     *     
     */
    public WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW getWSCCOMPANYCRRESULTW() {
        return wsccompanycrresultw;
    }

    /**
     * Sets the value of the wsccompanycrresultw property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW }
     *     
     */
    public void setWSCCOMPANYCRRESULTW(WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW value) {
        this.wsccompanycrresultw = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="RECORDS"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="COMPANY_CR_INFO_RS" type="{http://xmlns.oracle.com/orawsv/QUADRO_INTERFACE/WSC_GET_COMPANY_CR_INFO_P}COMPANY_CR_INFO_RS_IntType" maxOccurs="5000" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "records"
    })
    public static class WSCCOMPANYCRRESULTW {

        @XmlElement(name = "RECORDS", required = true)
        protected WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW.RECORDS records;

        /**
         * Gets the value of the records property.
         * 
         * @return
         *     possible object is
         *     {@link WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW.RECORDS }
         *     
         */
        public WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW.RECORDS getRECORDS() {
            return records;
        }

        /**
         * Sets the value of the records property.
         * 
         * @param value
         *     allowed object is
         *     {@link WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW.RECORDS }
         *     
         */
        public void setRECORDS(WSCCOMPANYCRRESULTWType.WSCCOMPANYCRRESULTW.RECORDS value) {
            this.records = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="COMPANY_CR_INFO_RS" type="{http://xmlns.oracle.com/orawsv/QUADRO_INTERFACE/WSC_GET_COMPANY_CR_INFO_P}COMPANY_CR_INFO_RS_IntType" maxOccurs="5000" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "companycrinfors"
        })
        public static class RECORDS {

            @XmlElement(name = "COMPANY_CR_INFO_RS")
            protected List<COMPANYCRINFORSIntType> companycrinfors;

            /**
             * Gets the value of the companycrinfors property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the companycrinfors property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCOMPANYCRINFORS().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link COMPANYCRINFORSIntType }
             * 
             * 
             */
            public List<COMPANYCRINFORSIntType> getCOMPANYCRINFORS() {
                if (companycrinfors == null) {
                    companycrinfors = new ArrayList<COMPANYCRINFORSIntType>();
                }
                return this.companycrinfors;
            }

        }

    }

}
