//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 11:14:16 AM EET 
//


package ekol.crm.account.wsclient.companycrinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="O_RECORDS" type="{http://xmlns.oracle.com/orawsv/QUADRO_INTERFACE/WSC_GET_COMPANY_CR_INFO_P}WSC_COMPANY_CR_RESULT_WType"/&gt;
 *         &lt;element name="O_RESULT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orecords",
    "oresult"
})
@XmlRootElement(name = "WSC_GET_COMPANY_CR_INFO_POutput")
public class WSCGETCOMPANYCRINFOPOutput {

    @XmlElement(name = "O_RECORDS", required = true)
    protected WSCCOMPANYCRRESULTWType orecords;
    @XmlElement(name = "O_RESULT", required = true)
    protected String oresult;

    /**
     * Gets the value of the orecords property.
     * 
     * @return
     *     possible object is
     *     {@link WSCCOMPANYCRRESULTWType }
     *     
     */
    public WSCCOMPANYCRRESULTWType getORECORDS() {
        return orecords;
    }

    /**
     * Sets the value of the orecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCCOMPANYCRRESULTWType }
     *     
     */
    public void setORECORDS(WSCCOMPANYCRRESULTWType value) {
        this.orecords = value;
    }

    /**
     * Gets the value of the oresult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORESULT() {
        return oresult;
    }

    /**
     * Sets the value of the oresult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORESULT(String value) {
        this.oresult = value;
    }

}
