//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 11:14:16 AM EET 
//


package ekol.crm.account.wsclient.companycrinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="I_OO_CMP_ID-NUMBER-IN" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="O_RECORDS-WSC_COMPANY_CR_RESULT_W-COUT"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="O_RESULT-VARCHAR2-OUT"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ioocmpidnumberin",
    "orecordswsccompanycrresultwcout",
    "oresultvarchar2OUT"
})
@XmlRootElement(name = "WSC_GET_COMPANY_CR_INFO_PInput")
public class WSCGETCOMPANYCRINFOPInput {

    @XmlElement(name = "I_OO_CMP_ID-NUMBER-IN")
    protected double ioocmpidnumberin;
    @XmlElement(name = "O_RECORDS-WSC_COMPANY_CR_RESULT_W-COUT", required = true)
    protected WSCGETCOMPANYCRINFOPInput.ORECORDSWSCCOMPANYCRRESULTWCOUT orecordswsccompanycrresultwcout;
    @XmlElement(name = "O_RESULT-VARCHAR2-OUT", required = true)
    protected WSCGETCOMPANYCRINFOPInput.ORESULTVARCHAR2OUT oresultvarchar2OUT;

    /**
     * Gets the value of the ioocmpidnumberin property.
     * 
     */
    public double getIOOCMPIDNUMBERIN() {
        return ioocmpidnumberin;
    }

    /**
     * Sets the value of the ioocmpidnumberin property.
     * 
     */
    public void setIOOCMPIDNUMBERIN(double value) {
        this.ioocmpidnumberin = value;
    }

    /**
     * Gets the value of the orecordswsccompanycrresultwcout property.
     * 
     * @return
     *     possible object is
     *     {@link WSCGETCOMPANYCRINFOPInput.ORECORDSWSCCOMPANYCRRESULTWCOUT }
     *     
     */
    public WSCGETCOMPANYCRINFOPInput.ORECORDSWSCCOMPANYCRRESULTWCOUT getORECORDSWSCCOMPANYCRRESULTWCOUT() {
        return orecordswsccompanycrresultwcout;
    }

    /**
     * Sets the value of the orecordswsccompanycrresultwcout property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCGETCOMPANYCRINFOPInput.ORECORDSWSCCOMPANYCRRESULTWCOUT }
     *     
     */
    public void setORECORDSWSCCOMPANYCRRESULTWCOUT(WSCGETCOMPANYCRINFOPInput.ORECORDSWSCCOMPANYCRRESULTWCOUT value) {
        this.orecordswsccompanycrresultwcout = value;
    }

    /**
     * Gets the value of the oresultvarchar2OUT property.
     * 
     * @return
     *     possible object is
     *     {@link WSCGETCOMPANYCRINFOPInput.ORESULTVARCHAR2OUT }
     *     
     */
    public WSCGETCOMPANYCRINFOPInput.ORESULTVARCHAR2OUT getORESULTVARCHAR2OUT() {
        return oresultvarchar2OUT;
    }

    /**
     * Sets the value of the oresultvarchar2OUT property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCGETCOMPANYCRINFOPInput.ORESULTVARCHAR2OUT }
     *     
     */
    public void setORESULTVARCHAR2OUT(WSCGETCOMPANYCRINFOPInput.ORESULTVARCHAR2OUT value) {
        this.oresultvarchar2OUT = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ORECORDSWSCCOMPANYCRRESULTWCOUT {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ORESULTVARCHAR2OUT {


    }

}
