server:
  port: 8760


oneorder:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@//10.1.70.92:49161/xe
    username: crmactivity
    password: 1234

spring:
  data:
    mongodb:
      host: 10.1.70.92
      port: 27017
      database: crm-activity
      authentication-database: crm-activity
      mechanism: SCRAM-SHA-1
  rabbitmq:
    host: 10.1.70.92
    port: 5672
  redis:
    host: 10.1.70.92
    port: 6379

security:
  host: 10.1.70.92
  oauth2:
    client:
      checkTokenUri: http://${security.host}:9999/auth/oauth/check_token
      accessTokenUri: http://${security.host}:9999/auth/oauth/token
      userAuthorizationUri: http://${security.host}:9999/auth/oauth/authorize
      clientId: oneorder
      clientSecret: oneorder
      scope: oneorder
    resource:
      userInfoUri: http://${security.host}:9999/auth/user

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://10.1.70.92:8761/eureka/
