//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 11:14:16 AM EET 
//


package ekol.crm.account.wsclient.companyblockage.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="O_BLOCKAGE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oblockagecode"
})
@XmlRootElement(name = "WSC_GET_COMPANY_BLOCKAGEOutput")
public class WSCGETCOMPANYBLOCKAGEOutput {

    @XmlElement(name = "O_BLOCKAGE_CODE", required = true)
    protected String oblockagecode;

    /**
     * Gets the value of the oblockagecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBLOCKAGECODE() {
        return oblockagecode;
    }

    /**
     * Sets the value of the oblockagecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBLOCKAGECODE(String value) {
        this.oblockagecode = value;
    }

}
